### ISSUE TITLE
support flat configs

### ISSUE THREAD

**Issue by aladdin-add** [ota-meshi/eslint-online-playground#67]

**Comment by ota-meshi** [comment]
Yeah, I've replaced some examples with it, but it will take some time to migrate all the examples.

https://eslint-online-playground.netlify.app/#eslint-plugin-markdown

**Comment by regseb** [comment]
I've created an example for [eslint-plugin-n#275](https://github.com/eslint-community/eslint-plugin-n/pull/275):

https://eslint-online-playground.netlify.app/#eNptjzFuwzAMRa8icGqB2NndtbcoOxgybaiVSUGSgxSG717KUoAMWSiReJ//c4cU7ZXu4xo89T8JBrDCSbTxsryFKJZS6olv7x/IcAFK3nHuFZrdUgVuDRKzYTNHWQ02pAt+Wxx3jKBKZLqf1ETzuPlsvpCN2UsxppJpMLsuOS51GDdPZVQ7o3v5ytK1RJ0mQhiKW4wSESp2lEfLdw0bRvs7LuUuYQ167kLIf4GqdpVJXRBOS4SJbp8UiCdi6ygVptk/jqoyP2ZK+m9JX1z8TLVIBxz/MqF45g==
