### ISSUE TITLE
Example `@sap/eslint-plugin-cds` does not work.

### ISSUE THREAD

**Issue by ota-meshi** [ota-meshi/eslint-online-playground#82]
It has probably been migrated to a flat configuration, but the examples have not been updated.

Reproduce Link:
https://eslint-online-playground.netlify.app/#@sap/eslint-plugin-cds

**Comment by ota-meshi** [comment]
Hi @mnkiefer 👋 
If you're interested, could you open a PR?

I'm in the process of migrating some plugins to a flat config.
https://eslint-online-playground.netlify.app/#eslint-plugin-n

**Comment by mnkiefer** [comment]
> Hi [Mara Nikola Kiefer](https://github.com/mnkiefer) 👋 If you're interested, could you open a PR?
> 
> I'm in the process of migrating some plugins to a flat config. https://eslint-online-playground.netlify.app/#eslint-plugin-n

@ota-meshi: Thanks for reaching out! :heart:  I recently changed jobs so I'm passing this onto the new maintainers of CDS lint.

@chgeo, @bugwelle: Can you take care of this from here please? 🙏

**Comment by chgeo** [comment]
> Reproduce Link:
> https://eslint-online-playground.netlify.app/#@sap/eslint-plugin-cds

I guess the sample code is stored here? https://github.com/ota-meshi/eslint-online-playground/tree/main/src/examples/plugin-eslint-plugin

@bugwelle @daogrady Can someone take this?

Note: In our [documentation](https://cap.cloud.sap/docs/tools/cds-lint/rules), we have already migrated our examples to flat config, see e.g. [this one](https://eslint-online-playground.netlify.app/#eNp9Ustu2zAQ/JUFL04Ai4rRQ1H14ha55NJLjmULM9JaZiw+SlJuVMP/3iVFOwkS5CKB3NmZ2VkeWfCHWnZamSqgP6gWedsF1rAxKNPDEYJ0vJVOeeQP1u7DzjqQAfQEJ9h6q2HBed091KHdoZaLr8IIU9fwwwI+uUG1KoLHEL1qo7ImgPP2oDrswBooirD5lgzcz6dN7pcRNmuPf0YSDhsuzBn7EgrrqzOkWSyuya0wAGiiihN8T26TVVJ8xKyeNPXEc4WMntiSXZyXsY3UGJwk7ncGz8O9oj8mwT1OcHcLDdyZiD16ggGstTSdjNZPQPgBgeqDbeWg/tHw9xSI6a9Wq9V1MYJhUCby1pqt6vlj8qK0sz4CGStJr8lTPQMrN4w9LY2Ki+zqKWM73MpxiPAzWaBa4QvcY2u1RkPJL1MtGweYWUJzPkMRSbRNIpivT7kHwI8DRf0MpkVxnpJ7T4dndOkEEOzMXMsx7ipjK9QuTtXL5yFYQ94Zem+9YEvBKPa/gv0qNtKPPnSkxGhLe9kjZWUNpZVNibzAxEIkc1CR6KvyBhJlRh3QB9KbgSt+w28upTi5QqBtRxNcCh26NJdpFWafJYXnueau358Fyz4vbYfbDzvfLLTwfCrKCThjSuFLEUgP5/QfNGJCXQ==).

**Comment by chgeo** [comment]
@ota-meshi Bonus problem: the playground seems to be broken atm, as the source code editor cannot be loaded due to 404 from https://cdnjs.cloudflare.com/ajax/libs/monaco-editor/0.50.0/min/vs/loader.min.js

**Comment by ota-meshi** [comment]
@mnkiefer Wow! I wish you the best of luck in your new job ❤️ 

@chgeo Thank you for letting me know! I reverted monaco-editor to 0.49. #84

**Comment by ota-meshi** [comment]
> I guess the sample code is stored here? https://github.com/ota-meshi/eslint-online-playground/tree/main/src/examples/plugin-eslint-plugin

I recommend you to refer to the following directory:

https://github.com/ota-meshi/eslint-online-playground/tree/main/src/examples/plugin-n

**Comment by ota-meshi** [comment]
Oh, I just realized that the plugin installer doesn't work either.

If you want it to work, could you also fix the following file?

https://github.com/ota-meshi/eslint-online-playground/blob/main/src/plugins/plugins/cds/plugin.ts

I think the following file will be helpful:

https://github.com/ota-meshi/eslint-online-playground/tree/main/src/plugins/plugins/n/plugin.ts

**Comment by ota-meshi** [comment]
@chgeo 
> @bugwelle @daogrady Can someone take this?

If it is difficult to maintain, we can also remove the code related to `@sap/eslint-plugin-cds` from this repository.
As you already know, you can also use the playground by using a link with a hash.

**Comment by chgeo** [comment]
> If it is difficult to maintain, we can also remove the code related to `@sap/eslint-plugin-cds` from this repository. As you already know, you can also use the playground by using a link with a hash 😉

Good point.  It's not hard to maintain, but yet another code location that we need to be aware of.  So what about removing the sample code here, but provide a link to our [documentation page](https://cap.cloud.sap/docs/tools/cds-lint/rules) with more examples for the playground?

**Comment by ota-meshi** [comment]
Either is fine with me :wink: 
Personally, I'd like to see more use cases for the plugin in the playground, but I don't use `@sap/eslint-plugin-cds`, so I can't maintain it :sweat: 
If maintaining it becomes too costly for you, I think removing it from the playground is a good option.

**Comment by daogrady** [comment]
Hi everyone,

thanks for bringing this to our attention @ota-meshi.
I will look into the issue and fix it asap to get this back into a working state and we can then discuss how to continue from there.

Best,
Daniel
